name: Automerge dependabot pr

on: pull_request


jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    name: Auto-merge patch updates
    runs-on: ubuntu-latest
    steps:
      - uses: mitto98/dependabot-automerge-action@master
        with:
          token: ${{ github.token }}
          merge-patch: true