# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths-ignore:
      - ".github/**"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set variables
        id: set_vars
        run: |
          DATE="$(date +%Y%m%d%H%M)"

          echo "DATE=${DATE}" >> $GITHUB_ENV

      - name: Set Commit
        id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Cache Gradle User Files
        uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-user-home

      - name: Cache Gradle Files
        uses: actions/cache@v4
        with:
          path: ./.gradle
          key: ${{ runner.os }}-gradle-file

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: |
          ./gradlew cleanBuild remapSpigotJar idea --no-daemon -i --stacktrace --refresh-dependencies
          ./gradlew build collect --no-daemon -i --stacktrace
          mv ./build/libs/*.jar ./build/libs/Fluorite-1.19.2-server.jar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Fluorite-1.19.2-${{ env.DATE }}
          path: ./build/libs/*.jar

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          commit: main
          tag: ${{ steps.commit.outputs.short }}
          name: Fluorite-1.19.2-server-${{ steps.commit.outputs.short }}
          artifacts: "./build/libs/*.jar"
